name: Generate Presentation

on:
  push:
    tags:
      - 'v*'  # Запуск при создании тега (например v1.0)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build with Maven
        run: mvn clean package
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/tourism-lean-presentation.pptx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}